language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-27.0.0
    - android-27
    - extra-android-m2repository
    - extra-google-m2repository
  licenses:
    - android-sdk-license-.+
    - '.+'

before_install:
  - yes | sdkmanager "platforms;android-27"

script: ./gradlew app:assemble app:check

branches:
  only:
    - master
    - develop
